steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/language-moress/banchanxanh-hp', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/language-moress/banchanxanh-hp']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'banchanxanh-hp', '--image', 'gcr.io/language-moress/banchanxanh-hp', '--region', 'asia-northeast1', '--platform', 'managed']
images:
  - gcr.io/language-moress/banchanxanh-hp
